// Maps every country/territory used in the curated roster to one of six
// continents, so the app can surface "how much of the world have you seen."
export type Continent = 'Africa' | 'Asia' | 'Europe' | 'North America' | 'South America' | 'Oceania';

export const CONTINENT_COUNT = 6;

const COUNTRY_CONTINENT: Record<string, Continent> = {
  'Albania': 'Europe',
  'Algeria': 'Africa',
  'Argentina': 'South America',
  'Armenia': 'Asia',
  'Australia': 'Oceania',
  'Austria': 'Europe',
  'Azerbaijan': 'Asia',
  'Bahamas': 'North America',
  'Bangladesh': 'Asia',
  'Barbados': 'North America',
  'Belgium': 'Europe',
  'Belize': 'North America',
  'Bhutan': 'Asia',
  'Bolivia': 'South America',
  'Bosnia and Herzegovina': 'Europe',
  'Botswana': 'Africa',
  'Brazil': 'South America',
  'Brunei': 'Asia',
  'Bulgaria': 'Europe',
  'Cambodia': 'Asia',
  'Canada': 'North America',
  'Cape Verde': 'Africa',
  'Chile': 'South America',
  'China': 'Asia',
  'Colombia': 'South America',
  'Cook Islands': 'Oceania',
  'Costa Rica': 'North America',
  'Croatia': 'Europe',
  'Cuba': 'North America',
  'Cyprus': 'Europe',
  'Czech Republic': 'Europe',
  'Democratic Republic of the Congo': 'Africa',
  'Denmark': 'Europe',
  'Djibouti': 'Africa',
  'Dominican Republic': 'North America',
  'Ecuador': 'South America',
  'Egypt': 'Africa',
  'El Salvador': 'North America',
  'Estonia': 'Europe',
  'Eswatini': 'Africa',
  'Ethiopia': 'Africa',
  'Fiji': 'Oceania',
  'Finland': 'Europe',
  'France': 'Europe',
  'French Polynesia': 'Oceania',
  'Georgia': 'Asia',
  'Germany': 'Europe',
  'Ghana': 'Africa',
  'Greece': 'Europe',
  'Guatemala': 'North America',
  'Guyana': 'South America',
  'Honduras': 'North America',
  'Hong Kong': 'Asia',
  'Hungary': 'Europe',
  'Iceland': 'Europe',
  'India': 'Asia',
  'Indonesia': 'Asia',
  'Iran': 'Asia',
  'Ireland': 'Europe',
  'Israel': 'Asia',
  'Italy': 'Europe',
  'Ivory Coast': 'Africa',
  'Jamaica': 'North America',
  'Japan': 'Asia',
  'Jordan': 'Asia',
  'Kazakhstan': 'Asia',
  'Kenya': 'Africa',
  'Kiribati': 'Oceania',
  'Kyrgyzstan': 'Asia',
  'Laos': 'Asia',
  'Latvia': 'Europe',
  'Lebanon': 'Asia',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'Madagascar': 'Africa',
  'Malawi': 'Africa',
  'Malaysia': 'Asia',
  'Maldives': 'Asia',
  'Mali': 'Africa',
  'Malta': 'Europe',
  'Marshall Islands': 'Oceania',
  'Mauritius': 'Africa',
  'Mexico': 'North America',
  'Micronesia': 'Oceania',
  'Monaco': 'Europe',
  'Mongolia': 'Asia',
  'Montenegro': 'Europe',
  'Morocco': 'Africa',
  'Mozambique': 'Africa',
  'Myanmar': 'Asia',
  'Namibia': 'Africa',
  'Nepal': 'Asia',
  'Netherlands': 'Europe',
  'New Caledonia': 'Oceania',
  'New Zealand': 'Oceania',
  'Nicaragua': 'North America',
  'Nigeria': 'Africa',
  'North Macedonia': 'Europe',
  'Norway': 'Europe',
  'Oman': 'Asia',
  'Pakistan': 'Asia',
  'Palau': 'Oceania',
  'Panama': 'North America',
  'Papua New Guinea': 'Oceania',
  'Paraguay': 'South America',
  'Peru': 'South America',
  'Philippines': 'Asia',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Puerto Rico': 'North America',
  'Qatar': 'Asia',
  'Romania': 'Europe',
  'Russia': 'Europe',
  'Rwanda': 'Africa',
  'Samoa': 'Oceania',
  'Saudi Arabia': 'Asia',
  'Senegal': 'Africa',
  'Serbia': 'Europe',
  'Seychelles': 'Africa',
  'Singapore': 'Asia',
  'Slovenia': 'Europe',
  'Solomon Islands': 'Oceania',
  'South Africa': 'Africa',
  'South Korea': 'Asia',
  'Spain': 'Europe',
  'Sri Lanka': 'Asia',
  'Sudan': 'Africa',
  'Suriname': 'South America',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'Taiwan': 'Asia',
  'Tanzania': 'Africa',
  'Thailand': 'Asia',
  'Tonga': 'Oceania',
  'Trinidad and Tobago': 'North America',
  'Tunisia': 'Africa',
  'Turkey': 'Asia',
  'Uganda': 'Africa',
  'Ukraine': 'Europe',
  'United Arab Emirates': 'Asia',
  'United Kingdom': 'Europe',
  'United States': 'North America',
  'Uruguay': 'South America',
  'Uzbekistan': 'Asia',
  'Vanuatu': 'Oceania',
  'Vatican City': 'Europe',
  'Venezuela': 'South America',
  'Vietnam': 'Asia',
  'Zambia': 'Africa',
  'Zimbabwe': 'Africa',
};

/** Falls back to undefined for user-added custom places in countries outside the curated roster. */
export function continentOf(country: string): Continent | undefined {
  return COUNTRY_CONTINENT[country];
}
