// Curated landmark roster. art_key maps to the client-side silhouette registry
// (client/src/art/landmarks.ts) — keep the two in sync when adding landmarks.
// Also mirrored in client/src/data/seedPlaces.ts for the static demo build.
export interface SeedPlace {
  name: string;
  country: string;
  description: string;
  lat: number;
  lng: number;
  artKey: string | null;
}

export const CURATED_PLACES: SeedPlace[] = [
  {
    name: 'Eiffel Tower',
    country: 'France',
    description: 'Iron lattice reaching for the Paris sky since 1889 — the city of light’s eternal exclamation mark.',
    lat: 48.8584,
    lng: 2.2945,
    artKey: 'eiffel',
  },
  {
    name: 'Statue of Liberty',
    country: 'United States',
    description: 'Lady Liberty lifts her torch over New York Harbor, greeting travelers as she has since 1886.',
    lat: 40.6892,
    lng: -74.0445,
    artKey: 'liberty',
  },
  {
    name: 'Big Ben',
    country: 'United Kingdom',
    description: 'The great bell of Westminster keeps London’s time, chiming above the Thames in Gothic splendour.',
    lat: 51.5007,
    lng: -0.1246,
    artKey: 'bigben',
  },
  {
    name: 'Colosseum',
    country: 'Italy',
    description: 'Rome’s mighty amphitheatre of stone arches, where fifty thousand voices once roared.',
    lat: 41.8902,
    lng: 12.4922,
    artKey: 'colosseum',
  },
  {
    name: 'Taj Mahal',
    country: 'India',
    description: 'A marble love letter on the Yamuna’s banks, glowing rose and ivory at dawn.',
    lat: 27.1751,
    lng: 78.0421,
    artKey: 'tajmahal',
  },
  {
    name: 'Great Pyramid of Giza',
    country: 'Egypt',
    description: 'Four and a half millennia of desert sun on the last standing wonder of the ancient world.',
    lat: 29.9792,
    lng: 31.1342,
    artKey: 'pyramids',
  },
  {
    name: 'Sydney Opera House',
    country: 'Australia',
    description: 'White sails billowing on Bennelong Point — the harbour’s grandest performance.',
    lat: -33.8568,
    lng: 151.2153,
    artKey: 'operahouse',
  },
  {
    name: 'Golden Gate Bridge',
    country: 'United States',
    description: 'International-orange towers striding through the fog at the gate of the Pacific.',
    lat: 37.8199,
    lng: -122.4783,
    artKey: 'goldengate',
  },
  {
    name: 'Christ the Redeemer',
    country: 'Brazil',
    description: 'Arms open wide above Rio, embracing beaches, samba, and the Sugarloaf below.',
    lat: -22.9519,
    lng: -43.2105,
    artKey: 'redeemer',
  },
  {
    name: 'Machu Picchu',
    country: 'Peru',
    description: 'The lost citadel of the Incas, terraced into cloud forest high above the Urubamba.',
    lat: -13.1631,
    lng: -72.545,
    artKey: 'machu',
  },
  {
    name: 'Mount Fuji',
    country: 'Japan',
    description: 'The sacred snow-capped cone rising in perfect symmetry over lakes and pine.',
    lat: 35.3606,
    lng: 138.7274,
    artKey: 'fuji',
  },
  {
    name: 'Fushimi Inari Shrine',
    country: 'Japan',
    description: 'Ten thousand vermilion torii gates winding up the wooded slopes of Kyoto.',
    lat: 34.9671,
    lng: 135.7727,
    artKey: 'torii',
  },
  {
    name: 'Sagrada Família',
    country: 'Spain',
    description: 'Gaudí’s unfinished symphony in stone, its spires still climbing over Barcelona.',
    lat: 41.4036,
    lng: 2.1744,
    artKey: 'sagrada',
  },
  {
    name: 'Brandenburg Gate',
    country: 'Germany',
    description: 'Berlin’s neoclassical triumph, where the Quadriga rides toward a reunited city.',
    lat: 52.5163,
    lng: 13.3777,
    artKey: 'brandenburg',
  },
  {
    name: 'Burj Khalifa',
    country: 'United Arab Emirates',
    description: 'A silver needle stitching the Dubai desert to the clouds — the world’s tallest view.',
    lat: 25.1972,
    lng: 55.2744,
    artKey: 'burj',
  },
  {
    name: 'Petra',
    country: 'Jordan',
    description: 'The rose-red Treasury carved into a desert canyon, revealed by a crack in the rock.',
    lat: 30.3285,
    lng: 35.4444,
    artKey: 'petra',
  },
  {
    name: 'Angkor Wat',
    country: 'Cambodia',
    description: 'Lotus-bud towers mirrored in still water — the largest temple the world has known.',
    lat: 13.4125,
    lng: 103.867,
    artKey: 'angkor',
  },
  {
    name: 'Great Wall at Mutianyu',
    country: 'China',
    description: 'Watchtowers riding the ridgelines, a stone dragon asleep across the mountains.',
    lat: 40.4319,
    lng: 116.5704,
    artKey: 'greatwall',
  },
  {
    name: 'Moai of Rapa Nui',
    country: 'Chile',
    description: 'Silent stone ancestors gazing inland over the loneliest island in the sea.',
    lat: -27.1258,
    lng: -109.2769,
    artKey: 'moai',
  },
  {
    name: 'Table Mountain',
    country: 'South Africa',
    description: 'A flat-topped sentinel draped in its tablecloth of cloud above Cape Town.',
    lat: -33.9628,
    lng: 18.4098,
    artKey: 'tablemountain',
  },
  {
    name: 'Niagara Falls',
    country: 'Canada',
    description: 'A thundering horseshoe of white water on the border of two nations.',
    lat: 43.0962,
    lng: -79.0377,
    artKey: 'niagara',
  },
  {
    name: 'Oia, Santorini',
    country: 'Greece',
    description: 'Whitewashed houses and blue domes tumbling down the caldera into the Aegean.',
    lat: 36.4618,
    lng: 25.3753,
    artKey: 'santorini',
  },
  {
    name: 'Neuschwanstein Castle',
    country: 'Germany',
    description: 'The fairy-tale king’s castle of turrets and towers, adrift in Alpine mist.',
    lat: 47.5576,
    lng: 10.7498,
    artKey: 'neuschwanstein',
  },
  {
    name: 'Acropolis of Athens',
    country: 'Greece',
    description: 'The Parthenon’s marble columns catching golden light above the ancient city.',
    lat: 37.9715,
    lng: 23.7267,
    artKey: 'acropolis',
  },
  {
    name: 'Gyeongbokgung Palace',
    country: 'South Korea',
    description: 'Joseon-dynasty pavilions and guard changes beneath Seoul’s mountain skyline.',
    lat: 37.5796,
    lng: 126.977,
    artKey: null,
  },
  {
    name: 'Wat Arun',
    country: 'Thailand',
    description: 'The Temple of Dawn glitters with porcelain mosaics on the banks of the Chao Phraya.',
    lat: 13.7437,
    lng: 100.4888,
    artKey: null,
  },
  {
    name: 'Ha Long Bay',
    country: 'Vietnam',
    description: 'Thousands of limestone karsts rising from emerald water, wrapped in legend.',
    lat: 20.9101,
    lng: 107.1839,
    artKey: null,
  },
  {
    name: 'Borobudur',
    country: 'Indonesia',
    description: 'The world’s largest Buddhist temple, its stupas watching the Java mist lift at dawn.',
    lat: -7.6079,
    lng: 110.2038,
    artKey: null,
  },
  {
    name: 'Chocolate Hills',
    country: 'Philippines',
    description: 'Over a thousand cone-shaped hills turning cocoa-brown across Bohol in the dry season.',
    lat: 9.8167,
    lng: 124.1667,
    artKey: null,
  },
  {
    name: 'Petronas Towers',
    country: 'Malaysia',
    description: 'Twin steel spires linked by a skybridge, once the tallest buildings on Earth.',
    lat: 3.1579,
    lng: 101.7116,
    artKey: null,
  },
  {
    name: 'Marina Bay Sands',
    country: 'Singapore',
    description: 'A rooftop infinity pool crowning three towers above the Lion City’s skyline.',
    lat: 1.2834,
    lng: 103.8607,
    artKey: null,
  },
  {
    name: 'Boudhanath Stupa',
    country: 'Nepal',
    description: 'Painted eyes gaze from every direction over Kathmandu’s largest Buddhist stupa.',
    lat: 27.7215,
    lng: 85.362,
    artKey: null,
  },
  {
    name: 'Sigiriya',
    country: 'Sri Lanka',
    description: 'An ancient rock fortress rising sheer from the jungle, frescoes still bright on its flank.',
    lat: 7.957,
    lng: 80.7603,
    artKey: null,
  },
  {
    name: 'Shwedagon Pagoda',
    country: 'Myanmar',
    description: 'A gilded stupa said to enshrine relics of four Buddhas, glowing over Yangon at dusk.',
    lat: 16.7983,
    lng: 96.1495,
    artKey: null,
  },
  {
    name: 'Genghis Khan Equestrian Statue',
    country: 'Mongolia',
    description: 'The largest equestrian statue in the world, steel and steppe wind on the Mongolian plain.',
    lat: 47.8467,
    lng: 106.9633,
    artKey: null,
  },
  {
    name: 'Hagia Sophia',
    country: 'Turkey',
    description: 'Byzantine dome and Ottoman minarets layered into one building across fifteen centuries.',
    lat: 41.0086,
    lng: 28.9802,
    artKey: null,
  },
  {
    name: 'Western Wall',
    country: 'Israel',
    description: 'The last remnant of the Second Temple, notes tucked into every reachable crevice.',
    lat: 31.7767,
    lng: 35.2345,
    artKey: null,
  },
  {
    name: 'Masjid al-Haram',
    country: 'Saudi Arabia',
    description: 'Islam’s holiest site, encircling the Kaaba at the heart of Mecca.',
    lat: 21.4225,
    lng: 39.8262,
    artKey: null,
  },
  {
    name: 'Museum of Islamic Art',
    country: 'Qatar',
    description: 'I.M. Pei’s limestone geometry standing on its own island in Doha Bay.',
    lat: 25.2949,
    lng: 51.539,
    artKey: null,
  },
  {
    name: 'Saint Basil’s Cathedral',
    country: 'Russia',
    description: 'Swirling onion domes in candy colors anchoring the south end of Red Square.',
    lat: 55.7525,
    lng: 37.6231,
    artKey: null,
  },
  {
    name: 'Bayterek Tower',
    country: 'Kazakhstan',
    description: 'A golden orb atop a white lattice tower, the mythic tree of life reimagined in steel.',
    lat: 51.1284,
    lng: 71.4306,
    artKey: null,
  },
  {
    name: 'Zaanse Schans Windmills',
    country: 'Netherlands',
    description: 'Working windmills line the Zaan, sails turning as they have for three centuries.',
    lat: 52.4747,
    lng: 4.8172,
    artKey: null,
  },
  {
    name: 'Belém Tower',
    country: 'Portugal',
    description: 'A Manueline fortress that watched Portugal’s caravels sail for the New World.',
    lat: 38.6916,
    lng: -9.216,
    artKey: null,
  },
  {
    name: 'Cliffs of Moher',
    country: 'Ireland',
    description: 'Sheer Atlantic cliffs climbing 700 feet above the crashing County Clare surf.',
    lat: 52.9715,
    lng: -9.4309,
    artKey: null,
  },
  {
    name: 'Gullfoss',
    country: 'Iceland',
    description: 'The Golden Falls thunder into a jagged canyon on Iceland’s Golden Circle.',
    lat: 64.3271,
    lng: -20.1199,
    artKey: null,
  },
  {
    name: 'Preikestolen',
    country: 'Norway',
    description: 'Pulpit Rock juts 600 meters above Lysefjord, a flat stone stage over the water.',
    lat: 58.9866,
    lng: 6.1902,
    artKey: null,
  },
  {
    name: 'Gamla Stan',
    country: 'Sweden',
    description: 'Cobbled medieval lanes and ochre façades on Stockholm’s old-town island.',
    lat: 59.3251,
    lng: 18.0711,
    artKey: null,
  },
  {
    name: 'The Little Mermaid',
    country: 'Denmark',
    description: 'A small bronze statue on a harbor rock, watching ferries leave Copenhagen.',
    lat: 55.6929,
    lng: 12.5993,
    artKey: null,
  },
  {
    name: 'Helsinki Cathedral',
    country: 'Finland',
    description: 'Neoclassical white and green domes crowning Senate Square in the midnight sun.',
    lat: 60.1699,
    lng: 24.9525,
    artKey: null,
  },
  {
    name: 'Matterhorn',
    country: 'Switzerland',
    description: 'A near-perfect pyramid of rock and ice, the most photographed peak in the Alps.',
    lat: 45.9763,
    lng: 7.6586,
    artKey: null,
  },
  {
    name: 'Hallstatt',
    country: 'Austria',
    description: 'A lakeside village of pastel houses stacked beneath alpine cliffs.',
    lat: 47.5622,
    lng: 13.6493,
    artKey: null,
  },
  {
    name: 'Charles Bridge',
    country: 'Czech Republic',
    description: 'Gothic statues line a stone bridge over the Vltava, Prague Castle floating above.',
    lat: 50.0865,
    lng: 14.4114,
    artKey: null,
  },
  {
    name: 'Hungarian Parliament Building',
    country: 'Hungary',
    description: 'Neo-Gothic spires and a river-facing façade lit gold along the Danube.',
    lat: 47.507,
    lng: 19.0458,
    artKey: null,
  },
  {
    name: 'Wawel Castle',
    country: 'Poland',
    description: 'A royal fortress of brick towers overlooking the Vistula in Kraków.',
    lat: 50.0544,
    lng: 19.9356,
    artKey: null,
  },
  {
    name: 'Dubrovnik Old Town',
    country: 'Croatia',
    description: 'Limestone walls encircle terracotta rooftops tumbling to the Adriatic.',
    lat: 42.6407,
    lng: 18.1077,
    artKey: null,
  },
  {
    name: 'Grand Place',
    country: 'Belgium',
    description: 'Gilded guild halls ring Brussels’ medieval market square.',
    lat: 50.8467,
    lng: 4.3525,
    artKey: null,
  },
  {
    name: 'Edinburgh Castle',
    country: 'United Kingdom',
    description: 'A fortress on an extinct volcano, guarding Scotland’s capital for nine centuries.',
    lat: 55.9486,
    lng: -3.1999,
    artKey: null,
  },
  {
    name: 'St. Peter’s Basilica',
    country: 'Vatican City',
    description: 'Michelangelo’s dome rises over the piazza at the heart of the Catholic world.',
    lat: 41.9022,
    lng: 12.4539,
    artKey: null,
  },
  {
    name: 'Monte Carlo Casino',
    country: 'Monaco',
    description: 'Belle Époque grandeur on the Riviera, roulette wheels spinning since 1863.',
    lat: 43.7396,
    lng: 7.4308,
    artKey: null,
  },
  {
    name: 'CN Tower',
    country: 'Canada',
    description: 'A concrete needle over Toronto with a glass floor not for the faint of heart.',
    lat: 43.6426,
    lng: -79.3871,
    artKey: null,
  },
  {
    name: 'Banff National Park',
    country: 'Canada',
    description: 'Turquoise glacial lakes ringed by the jagged peaks of the Canadian Rockies.',
    lat: 51.4968,
    lng: -115.9281,
    artKey: null,
  },
  {
    name: 'Chichén Itzá',
    country: 'Mexico',
    description: 'El Castillo’s stepped pyramid marks the equinox with a shadow-serpent on its stairs.',
    lat: 20.6843,
    lng: -88.5678,
    artKey: null,
  },
  {
    name: 'Tikal',
    country: 'Guatemala',
    description: 'Maya temple-pyramids break through the jungle canopy of the Petén rainforest.',
    lat: 17.222,
    lng: -89.6237,
    artKey: null,
  },
  {
    name: 'Old Havana',
    country: 'Cuba',
    description: 'Pastel colonial façades and vintage cars line streets facing the Malecón.',
    lat: 23.1367,
    lng: -82.3589,
    artKey: null,
  },
  {
    name: 'Dunn’s River Falls',
    country: 'Jamaica',
    description: 'Terraced limestone cascades tumble straight into the Caribbean Sea.',
    lat: 18.4139,
    lng: -77.1319,
    artKey: null,
  },
  {
    name: 'Iguazu Falls',
    country: 'Argentina',
    description: 'Hundreds of cataracts roar across the Argentina–Brazil border in a cloud of mist.',
    lat: -25.6953,
    lng: -54.4367,
    artKey: null,
  },
  {
    name: 'Torres del Paine',
    country: 'Chile',
    description: 'Granite towers pierce Patagonian sky above turquoise lakes and wind-bent trees.',
    lat: -50.9423,
    lng: -73.4068,
    artKey: null,
  },
  {
    name: 'Salar de Uyuni',
    country: 'Bolivia',
    description: 'The world’s largest salt flat turns into a mirror of the sky after rain.',
    lat: -20.1338,
    lng: -67.4891,
    artKey: null,
  },
  {
    name: 'Cartagena Old Town',
    country: 'Colombia',
    description: 'Walled colonial streets in every color, facing the Caribbean behind centuries-old ramparts.',
    lat: 10.4236,
    lng: -75.5482,
    artKey: null,
  },
  {
    name: 'Galápagos Islands',
    country: 'Ecuador',
    description: 'Volcanic islands where giant tortoises and finches inspired a theory of evolution.',
    lat: -0.9538,
    lng: -90.9656,
    artKey: null,
  },
  {
    name: 'Angel Falls',
    country: 'Venezuela',
    description: 'Water plunges nearly a kilometer off a tepui into the Venezuelan jungle below.',
    lat: 5.9701,
    lng: -62.5362,
    artKey: null,
  },
  {
    name: 'Jemaa el-Fnaa',
    country: 'Morocco',
    description: 'Snake charmers, spice stalls, and storytellers fill Marrakesh’s ancient main square at dusk.',
    lat: 31.6258,
    lng: -7.9891,
    artKey: null,
  },
  {
    name: 'Maasai Mara',
    country: 'Kenya',
    description: 'Endless savanna where wildebeest herds thunder across the Mara River each year.',
    lat: -1.5,
    lng: 35.1,
    artKey: null,
  },
  {
    name: 'Mount Kilimanjaro',
    country: 'Tanzania',
    description: 'Africa’s highest peak, snow-capped at the equator above the Tanzanian plains.',
    lat: -3.0674,
    lng: 37.3556,
    artKey: null,
  },
  {
    name: 'Victoria Falls',
    country: 'Zambia',
    description: 'The Zambezi plunges into a churning gorge in a curtain of spray visible for miles.',
    lat: -17.9243,
    lng: 25.8572,
    artKey: null,
  },
  {
    name: 'Sossusvlei',
    country: 'Namibia',
    description: 'Towering red dunes cradle a bone-white salt pan deep in the Namib Desert.',
    lat: -24.7333,
    lng: 15.3,
    artKey: null,
  },
  {
    name: 'Zuma Rock',
    country: 'Nigeria',
    description: 'A sheer 725-meter monolith standing sentinel over the road to Abuja.',
    lat: 9.1211,
    lng: 7.2062,
    artKey: null,
  },
  {
    name: 'Lalibela Rock Churches',
    country: 'Ethiopia',
    description: 'Eleven medieval churches carved downward into solid volcanic rock.',
    lat: 12.0316,
    lng: 39.0473,
    artKey: null,
  },
  {
    name: 'Amphitheatre of El Jem',
    country: 'Tunisia',
    description: 'A Roman colosseum rising improbably from the Tunisian plain, still nearly whole.',
    lat: 35.2967,
    lng: 10.705,
    artKey: null,
  },
  {
    name: 'Okavango Delta',
    country: 'Botswana',
    description: 'A river that never reaches the sea, fanning into a lush inland delta instead.',
    lat: -19.2833,
    lng: 22.9833,
    artKey: null,
  },
  {
    name: 'Cape Coast Castle',
    country: 'Ghana',
    description: 'Whitewashed ramparts on the Gulf of Guinea, holding centuries of hard history.',
    lat: 5.1053,
    lng: -1.2466,
    artKey: null,
  },
  {
    name: 'Milford Sound',
    country: 'New Zealand',
    description: 'Sheer fjord walls and waterfalls drop straight into still, dark water.',
    lat: -44.671,
    lng: 167.925,
    artKey: null,
  },
  {
    name: 'Bora Bora',
    country: 'French Polynesia',
    description: 'An extinct volcano ringed by a lagoon of impossible turquoise.',
    lat: -16.5004,
    lng: -151.7415,
    artKey: null,
  },
  {
    name: 'U.S. Space & Rocket Center',
    country: 'United States',
    description: 'Saturn V rockets stand on end where Huntsville helped put astronauts on the Moon.',
    lat: 34.7196,
    lng: -86.6503,
    artKey: null,
  },
  {
    name: 'Denali',
    country: 'United States',
    description: 'North America’s tallest peak, its own weather system wreathing the summit in cloud.',
    lat: 63.0692,
    lng: -151.007,
    artKey: null,
  },
  {
    name: 'Grand Canyon',
    country: 'United States',
    description: 'A mile-deep gash of banded red rock carved by the Colorado River over eons.',
    lat: 36.1069,
    lng: -112.1129,
    artKey: null,
  },
  {
    name: 'Hot Springs National Park',
    country: 'United States',
    description: 'Steaming thermal water still flows through this bathhouse row in the Ouachitas.',
    lat: 34.5037,
    lng: -93.0552,
    artKey: null,
  },
  {
    name: 'Yosemite Valley',
    country: 'United States',
    description: 'Granite cliffs and waterfalls tower over a valley carved by ancient glaciers.',
    lat: 37.7459,
    lng: -119.5936,
    artKey: null,
  },
  {
    name: 'Rocky Mountain National Park',
    country: 'United States',
    description: 'A road climbs above the treeline into tundra ringed by fourteen-thousand-foot peaks.',
    lat: 40.3428,
    lng: -105.6836,
    artKey: null,
  },
  {
    name: 'Mystic Seaport',
    country: 'United States',
    description: 'Tall ships and a recreated whaling village line the banks of the Mystic River.',
    lat: 41.3712,
    lng: -71.9662,
    artKey: null,
  },
  {
    name: 'Rehoboth Beach Boardwalk',
    country: 'United States',
    description: 'Saltwater taffy and Atlantic breeze along Delaware’s classic seaside boardwalk.',
    lat: 38.7209,
    lng: -75.076,
    artKey: null,
  },
  {
    name: 'Cinderella Castle',
    country: 'United States',
    description: 'A fairy-tale spire at the heart of the Magic Kingdom in Orlando.',
    lat: 28.4177,
    lng: -81.5812,
    artKey: null,
  },
  {
    name: 'Stone Mountain',
    country: 'United States',
    description: 'The largest exposed granite monolith on Earth, carved with a Confederate memorial relief.',
    lat: 33.8055,
    lng: -84.1455,
    artKey: null,
  },
  {
    name: 'Diamond Head',
    country: 'United States',
    description: 'A volcanic tuff cone crater standing guard over Waikiki Beach.',
    lat: 21.262,
    lng: -157.8058,
    artKey: null,
  },
  {
    name: 'Shoshone Falls',
    country: 'United States',
    description: 'The “Niagara of the West” drops over a horseshoe rim on the Snake River.',
    lat: 42.5946,
    lng: -114.4001,
    artKey: null,
  },
  {
    name: 'Cloud Gate',
    country: 'United States',
    description: 'A liquid-mercury sculpture — “The Bean” — mirrors Chicago’s skyline in Millennium Park.',
    lat: 41.8827,
    lng: -87.6233,
    artKey: null,
  },
  {
    name: 'Indianapolis Motor Speedway',
    country: 'United States',
    description: 'The “Brickyard” has hosted the Indy 500 on its oval since 1911.',
    lat: 39.795,
    lng: -86.2347,
    artKey: null,
  },
  {
    name: 'Field of Dreams',
    country: 'United States',
    description: 'A baseball diamond cut into an Iowa cornfield, straight out of the movie.',
    lat: 42.493,
    lng: -91.0182,
    artKey: null,
  },
  {
    name: 'Monument Rocks',
    country: 'United States',
    description: 'Chalk badland spires rise from the Kansas prairie, remnants of an ancient seabed.',
    lat: 38.7909,
    lng: -100.748,
    artKey: null,
  },
  {
    name: 'Mammoth Cave',
    country: 'United States',
    description: 'The longest known cave system on Earth, still being mapped beneath the Kentucky hills.',
    lat: 37.1862,
    lng: -86.1,
    artKey: null,
  },
  {
    name: 'French Quarter',
    country: 'United States',
    description: 'Wrought-iron balconies and jazz spill onto the streets of old New Orleans.',
    lat: 29.9584,
    lng: -90.0644,
    artKey: null,
  },
  {
    name: 'Acadia National Park',
    country: 'United States',
    description: 'Pink granite headlands meet the Atlantic where the sunrise hits the U.S. first.',
    lat: 44.3386,
    lng: -68.2733,
    artKey: null,
  },
  {
    name: 'Fort McHenry',
    country: 'United States',
    description: 'The star-shaped fort whose overnight bombardment inspired the national anthem.',
    lat: 39.2627,
    lng: -76.5797,
    artKey: null,
  },
  {
    name: 'Bunker Hill Monument',
    country: 'United States',
    description: 'A granite obelisk on Boston’s Freedom Trail marks the Revolution’s bloodiest battle.',
    lat: 42.3763,
    lng: -71.0611,
    artKey: null,
  },
  {
    name: 'Mackinac Bridge',
    country: 'United States',
    description: 'A five-mile suspension bridge links Michigan’s two peninsulas over the Straits.',
    lat: 45.818,
    lng: -84.7278,
    artKey: null,
  },
  {
    name: 'Split Rock Lighthouse',
    country: 'United States',
    description: 'A century-old beacon on a sheer cliff above the vast, cold expanse of Lake Superior.',
    lat: 47.2,
    lng: -91.3675,
    artKey: null,
  },
  {
    name: 'Vicksburg National Military Park',
    country: 'United States',
    description: 'Monuments and earthworks mark the Civil War siege that split the Confederacy.',
    lat: 32.3466,
    lng: -90.857,
    artKey: null,
  },
  {
    name: 'Gateway Arch',
    country: 'United States',
    description: 'A gleaming stainless-steel catenary curve framing the St. Louis riverfront.',
    lat: 38.6247,
    lng: -90.1848,
    artKey: null,
  },
  {
    name: 'Glacier National Park',
    country: 'United States',
    description: 'The Going-to-the-Sun Road climbs through jagged peaks and ancient ice fields.',
    lat: 48.696,
    lng: -113.718,
    artKey: null,
  },
  {
    name: 'Chimney Rock',
    country: 'United States',
    description: 'A slender spire that guided a century of wagon trains along the Oregon Trail.',
    lat: 41.7027,
    lng: -103.348,
    artKey: null,
  },
  {
    name: 'Hoover Dam',
    country: 'United States',
    description: 'An Art Deco curve of concrete holding back the Colorado River in Black Canyon.',
    lat: 36.0161,
    lng: -114.7377,
    artKey: null,
  },
  {
    name: 'Mount Washington',
    country: 'United States',
    description: 'The Northeast’s highest peak, once clocked with the fastest surface wind on Earth.',
    lat: 44.2706,
    lng: -71.3033,
    artKey: null,
  },
  {
    name: 'Atlantic City Boardwalk',
    country: 'United States',
    description: 'The original boardwalk, saltwater taffy, casinos, and the Atlantic all in a row.',
    lat: 39.3643,
    lng: -74.4229,
    artKey: null,
  },
  {
    name: 'White Sands',
    country: 'United States',
    description: 'Gypsum dunes ripple white to the horizon in the Tularosa Basin.',
    lat: 32.7871,
    lng: -106.3255,
    artKey: null,
  },
  {
    name: 'Empire State Building',
    country: 'United States',
    description: 'An Art Deco spire that ruled the Manhattan skyline for four decades.',
    lat: 40.7484,
    lng: -73.9857,
    artKey: null,
  },
  {
    name: 'Wright Brothers National Memorial',
    country: 'United States',
    description: 'The dunes of Kitty Hawk where twelve seconds of flight changed the world.',
    lat: 36.0128,
    lng: -75.6707,
    artKey: null,
  },
  {
    name: 'Theodore Roosevelt National Park',
    country: 'United States',
    description: 'Painted badlands and bison roam the park named for its conservationist president.',
    lat: 46.9789,
    lng: -103.5382,
    artKey: null,
  },
  {
    name: 'Rock & Roll Hall of Fame',
    country: 'United States',
    description: 'A glass pyramid on Lake Erie’s shore honoring music’s loudest rebels.',
    lat: 41.5087,
    lng: -81.695,
    artKey: null,
  },
  {
    name: 'Oklahoma City National Memorial',
    country: 'United States',
    description: 'A field of empty chairs and a reflecting pool mark a moment of resilience.',
    lat: 35.473,
    lng: -97.5171,
    artKey: null,
  },
  {
    name: 'Crater Lake',
    country: 'United States',
    description: 'The deepest lake in the U.S. fills a collapsed volcano with impossibly blue water.',
    lat: 42.9446,
    lng: -122.109,
    artKey: null,
  },
  {
    name: 'Liberty Bell',
    country: 'United States',
    description: 'A cracked bronze bell in Philadelphia, rung to proclaim American independence.',
    lat: 39.9496,
    lng: -75.1503,
    artKey: null,
  },
  {
    name: 'The Breakers',
    country: 'United States',
    description: 'A Gilded Age Vanderbilt mansion overlooking the cliffs of Newport.',
    lat: 41.4694,
    lng: -71.2999,
    artKey: null,
  },
  {
    name: 'Fort Sumter',
    country: 'United States',
    description: 'The harbor fort where the first shots of the Civil War were fired.',
    lat: 32.7523,
    lng: -79.8748,
    artKey: null,
  },
  {
    name: 'Mount Rushmore',
    country: 'United States',
    description: 'Four presidents’ faces carved sixty feet tall into the Black Hills granite.',
    lat: 43.8791,
    lng: -103.4591,
    artKey: null,
  },
  {
    name: 'Great Smoky Mountains',
    country: 'United States',
    description: 'Blue-hazed ridgelines roll to the horizon in America’s most-visited national park.',
    lat: 35.6118,
    lng: -83.4895,
    artKey: null,
  },
  {
    name: 'The Alamo',
    country: 'United States',
    description: 'A former mission in San Antonio, remembered for a thirteen-day siege in 1836.',
    lat: 29.426,
    lng: -98.4861,
    artKey: null,
  },
  {
    name: 'Arches National Park',
    country: 'United States',
    description: 'Over two thousand natural sandstone arches rise from Utah’s red desert.',
    lat: 38.7331,
    lng: -109.5925,
    artKey: null,
  },
  {
    name: 'Vermont State House',
    country: 'United States',
    description: 'A gold-domed capitol standing against Vermont’s forested Green Mountains.',
    lat: 44.2601,
    lng: -72.5754,
    artKey: null,
  },
  {
    name: 'Monticello',
    country: 'United States',
    description: 'Thomas Jefferson’s neoclassical hilltop home, designed down to the last detail.',
    lat: 38.0084,
    lng: -78.4529,
    artKey: null,
  },
  {
    name: 'Space Needle',
    country: 'United States',
    description: 'A flying-saucer-topped tower built for the 1962 World’s Fair, still Seattle’s icon.',
    lat: 47.6205,
    lng: -122.3493,
    artKey: null,
  },
  {
    name: 'New River Gorge Bridge',
    country: 'United States',
    description: 'One of the world’s highest steel arch bridges, spanning an ancient river gorge.',
    lat: 38.0676,
    lng: -81.0778,
    artKey: null,
  },
  {
    name: 'Wisconsin Dells',
    country: 'United States',
    description: 'Sandstone canyons carved by glacial floodwaters along the Wisconsin River.',
    lat: 43.6274,
    lng: -89.771,
    artKey: null,
  },
  {
    name: 'Old Faithful',
    country: 'United States',
    description: 'Yellowstone’s most punctual geyser, erupting on a clockwork schedule since 1870.',
    lat: 44.4605,
    lng: -110.8281,
    artKey: null,
  },

];
