// Curated landmark roster. art_key maps to the client-side silhouette registry
// (client/src/art/landmarks.ts) — keep the two in sync when adding landmarks.
// Also mirrored in client/src/data/seedPlaces.ts for the static demo build.
export interface SeedPlace {
  name: string;
  country: string;
  description: string;
  lat: number;
  lng: number;
  artKey: string;
}

export const CURATED_PLACES: SeedPlace[] = [
  {
    name: 'Eiffel Tower',
    country: 'France',
    description: 'Iron lattice reaching for the Paris sky since 1889 — the city of light’s eternal exclamation mark.',
    lat: 48.8584,
    lng: 2.2945,
    artKey: 'eiffel',
  },
  {
    name: 'Statue of Liberty',
    country: 'United States',
    description: 'Lady Liberty lifts her torch over New York Harbor, greeting travelers as she has since 1886.',
    lat: 40.6892,
    lng: -74.0445,
    artKey: 'liberty',
  },
  {
    name: 'Big Ben',
    country: 'United Kingdom',
    description: 'The great bell of Westminster keeps London’s time, chiming above the Thames in Gothic splendour.',
    lat: 51.5007,
    lng: -0.1246,
    artKey: 'bigben',
  },
  {
    name: 'Colosseum',
    country: 'Italy',
    description: 'Rome’s mighty amphitheatre of stone arches, where fifty thousand voices once roared.',
    lat: 41.8902,
    lng: 12.4922,
    artKey: 'colosseum',
  },
  {
    name: 'Taj Mahal',
    country: 'India',
    description: 'A marble love letter on the Yamuna’s banks, glowing rose and ivory at dawn.',
    lat: 27.1751,
    lng: 78.0421,
    artKey: 'tajmahal',
  },
  {
    name: 'Great Pyramid of Giza',
    country: 'Egypt',
    description: 'Four and a half millennia of desert sun on the last standing wonder of the ancient world.',
    lat: 29.9792,
    lng: 31.1342,
    artKey: 'pyramids',
  },
  {
    name: 'Sydney Opera House',
    country: 'Australia',
    description: 'White sails billowing on Bennelong Point — the harbour’s grandest performance.',
    lat: -33.8568,
    lng: 151.2153,
    artKey: 'operahouse',
  },
  {
    name: 'Golden Gate Bridge',
    country: 'United States',
    description: 'International-orange towers striding through the fog at the gate of the Pacific.',
    lat: 37.8199,
    lng: -122.4783,
    artKey: 'goldengate',
  },
  {
    name: 'Christ the Redeemer',
    country: 'Brazil',
    description: 'Arms open wide above Rio, embracing beaches, samba, and the Sugarloaf below.',
    lat: -22.9519,
    lng: -43.2105,
    artKey: 'redeemer',
  },
  {
    name: 'Machu Picchu',
    country: 'Peru',
    description: 'The lost citadel of the Incas, terraced into cloud forest high above the Urubamba.',
    lat: -13.1631,
    lng: -72.545,
    artKey: 'machu',
  },
  {
    name: 'Mount Fuji',
    country: 'Japan',
    description: 'The sacred snow-capped cone rising in perfect symmetry over lakes and pine.',
    lat: 35.3606,
    lng: 138.7274,
    artKey: 'fuji',
  },
  {
    name: 'Fushimi Inari Shrine',
    country: 'Japan',
    description: 'Ten thousand vermilion torii gates winding up the wooded slopes of Kyoto.',
    lat: 34.9671,
    lng: 135.7727,
    artKey: 'torii',
  },
  {
    name: 'Sagrada Família',
    country: 'Spain',
    description: 'Gaudí’s unfinished symphony in stone, its spires still climbing over Barcelona.',
    lat: 41.4036,
    lng: 2.1744,
    artKey: 'sagrada',
  },
  {
    name: 'Brandenburg Gate',
    country: 'Germany',
    description: 'Berlin’s neoclassical triumph, where the Quadriga rides toward a reunited city.',
    lat: 52.5163,
    lng: 13.3777,
    artKey: 'brandenburg',
  },
  {
    name: 'Burj Khalifa',
    country: 'United Arab Emirates',
    description: 'A silver needle stitching the Dubai desert to the clouds — the world’s tallest view.',
    lat: 25.1972,
    lng: 55.2744,
    artKey: 'burj',
  },
  {
    name: 'Petra',
    country: 'Jordan',
    description: 'The rose-red Treasury carved into a desert canyon, revealed by a crack in the rock.',
    lat: 30.3285,
    lng: 35.4444,
    artKey: 'petra',
  },
  {
    name: 'Angkor Wat',
    country: 'Cambodia',
    description: 'Lotus-bud towers mirrored in still water — the largest temple the world has known.',
    lat: 13.4125,
    lng: 103.867,
    artKey: 'angkor',
  },
  {
    name: 'Great Wall at Mutianyu',
    country: 'China',
    description: 'Watchtowers riding the ridgelines, a stone dragon asleep across the mountains.',
    lat: 40.4319,
    lng: 116.5704,
    artKey: 'greatwall',
  },
  {
    name: 'Moai of Rapa Nui',
    country: 'Chile',
    description: 'Silent stone ancestors gazing inland over the loneliest island in the sea.',
    lat: -27.1258,
    lng: -109.2769,
    artKey: 'moai',
  },
  {
    name: 'Table Mountain',
    country: 'South Africa',
    description: 'A flat-topped sentinel draped in its tablecloth of cloud above Cape Town.',
    lat: -33.9628,
    lng: 18.4098,
    artKey: 'tablemountain',
  },
  {
    name: 'Niagara Falls',
    country: 'Canada',
    description: 'A thundering horseshoe of white water on the border of two nations.',
    lat: 43.0962,
    lng: -79.0377,
    artKey: 'niagara',
  },
  {
    name: 'Oia, Santorini',
    country: 'Greece',
    description: 'Whitewashed houses and blue domes tumbling down the caldera into the Aegean.',
    lat: 36.4618,
    lng: 25.3753,
    artKey: 'santorini',
  },
  {
    name: 'Neuschwanstein Castle',
    country: 'Germany',
    description: 'The fairy-tale king’s castle of turrets and towers, adrift in Alpine mist.',
    lat: 47.5576,
    lng: 10.7498,
    artKey: 'neuschwanstein',
  },
  {
    name: 'Acropolis of Athens',
    country: 'Greece',
    description: 'The Parthenon’s marble columns catching golden light above the ancient city.',
    lat: 37.9715,
    lng: 23.7267,
    artKey: 'acropolis',
  },
];
